"""initial schema — stage 1 tables

Revision ID: 0001
Revises:
Create Date: 2026-07-22

Hand-written (not autogenerated): the driver double-booking exclusion
constraint needs raw SQL since SQLAlchemy's Table/Column API can't express
`EXCLUDE USING gist`, so the whole migration is single-authored for
reviewability.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("telegram_id", sa.BigInteger(), unique=True),
        sa.Column("email", sa.String(255), unique=True),
        sa.Column("password_hash", sa.String(255)),
        sa.Column("role", sa.String(20), nullable=False, server_default="user"),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("full_name", sa.String(200)),
        sa.Column("phone", sa.String(32)),
        sa.Column("can_order", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.CheckConstraint("role in ('user','driver','admin')", name="ck_users_role"),
        sa.CheckConstraint("status in ('pending','verified','blocked')", name="ck_users_status"),
        sa.CheckConstraint(
            "telegram_id IS NOT NULL OR email IS NOT NULL", name="ck_users_identity_present"
        ),
    )

    op.create_table(
        "drivers",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("car_model", sa.String(100)),
        sa.Column("car_plate", sa.String(20)),
        sa.Column("car_color", sa.String(50)),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
    )

    op.create_table(
        "driver_schedule",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "driver_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("drivers.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.CheckConstraint("weekday between 0 and 6", name="ck_driver_schedule_weekday_range"),
    )
    op.create_index("ix_driver_schedule_driver_id", "driver_schedule", ["driver_id"])

    op.create_table(
        "driver_time_off",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "driver_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("drivers.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("period", postgresql.TSTZRANGE(), nullable=False),
        sa.Column("reason", sa.String(255)),
    )
    op.create_index("ix_driver_time_off_driver_id", "driver_time_off", ["driver_id"])

    op.create_table(
        "addresses",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("label", sa.String(100)),
        sa.Column("address_text", sa.String(500), nullable=False),
        sa.Column("lat", sa.Numeric(9, 6)),
        sa.Column("lon", sa.Numeric(9, 6)),
        sa.Column("is_favorite", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("last_used_at", sa.DateTime(timezone=True)),
    )
    op.create_index("ix_addresses_user_id", "addresses", ["user_id"])

    op.create_table(
        "orders",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "driver_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("drivers.id", ondelete="SET NULL"),
        ),
        sa.Column("status", sa.String(30), nullable=False, server_default="draft"),
        sa.Column("from_address", sa.String(500), nullable=False),
        sa.Column("from_lat", sa.Numeric(9, 6)),
        sa.Column("from_lon", sa.Numeric(9, 6)),
        sa.Column("to_address", sa.String(500), nullable=False),
        sa.Column("to_lat", sa.Numeric(9, 6)),
        sa.Column("to_lon", sa.Numeric(9, 6)),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("est_duration_min", sa.SmallInteger(), nullable=False, server_default="30"),
        sa.Column("est_distance_km", sa.Numeric(6, 2)),
        sa.Column("passengers", sa.SmallInteger(), nullable=False, server_default="1"),
        sa.Column("comment", sa.String(500)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.Column("cancel_reason", sa.String(255)),
        sa.Column("cancelled_by", sa.String(20)),
        sa.CheckConstraint(
            "status in ('draft','pending_driver','confirmed','driver_en_route','driver_arrived',"
            "'in_progress','completed','cancelled_by_user','cancelled_by_driver',"
            "'cancelled_by_admin','expired')",
            name="ck_orders_status",
        ),
    )
    op.create_index("ix_orders_user_id", "orders", ["user_id"])
    op.create_index("ix_orders_driver_id", "orders", ["driver_id"])
    op.create_index("ix_orders_scheduled_at", "orders", ["scheduled_at"])

    # Prevents double-booking a driver. Raw SQL: SQLAlchemy's Table/Column
    # API has no EXCLUDE USING gist representation. Partial: cancelled /
    # completed / expired orders don't block rebooking the same slot, and
    # unassigned drafts (driver_id IS NULL) are skipped entirely.
    #
    # GiST exclusion constraints require an IMMUTABLE index expression, but
    # `timestamptz + interval` is only STABLE in Postgres (its result can in
    # theory depend on the session TimeZone setting during the underlying
    # conversions) even though for two already-materialized instants the
    # arithmetic is deterministic. The standard, well-known workaround is to
    # wrap the range construction in a small SQL function explicitly
    # declared IMMUTABLE — safe here since scheduled_at/est_duration_min are
    # fixed columns, not `now()`-derived values.
    op.execute(
        """
        CREATE FUNCTION order_busy_range(scheduled_at timestamptz, duration_min smallint)
        RETURNS tstzrange
        LANGUAGE sql
        IMMUTABLE
        AS $$
          SELECT tstzrange(
            scheduled_at,
            scheduled_at + (COALESCE(duration_min, 0) + 15) * interval '1 minute',
            '[)'
          )
        $$
        """
    )
    op.execute(
        """
        ALTER TABLE orders
          ADD CONSTRAINT excl_orders_driver_overlap
          EXCLUDE USING gist (
            driver_id WITH =,
            order_busy_range(scheduled_at, est_duration_min) WITH &&
          )
          WHERE (
            driver_id IS NOT NULL
            AND status NOT IN (
              'completed','cancelled_by_user','cancelled_by_driver','cancelled_by_admin','expired'
            )
          )
        """
    )

    op.create_table(
        "order_events",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "order_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("orders.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(50), nullable=False),
        sa.Column(
            "actor_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
        ),
        sa.Column("payload", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_index("ix_order_events_order_id", "order_events", ["order_id"])

    op.create_table(
        "verification_codes",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("code_hash", sa.String(255), nullable=False),
        sa.Column("channel", sa.String(20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), nullable=False, server_default="0"),
        sa.CheckConstraint("channel in ('email','phone')", name="ck_verification_codes_channel"),
    )
    op.create_index("ix_verification_codes_user_id", "verification_codes", ["user_id"])

    op.create_table(
        "settings",
        sa.Column("key", sa.String(100), primary_key=True),
        sa.Column("value", postgresql.JSONB(), nullable=False),
    )

    op.create_table(
        "push_subscriptions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("endpoint", sa.String(1000), nullable=False),
        sa.Column("p256dh", sa.String(255), nullable=False),
        sa.Column("auth", sa.String(255), nullable=False),
        sa.Column("user_agent", sa.String(255)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
        sa.UniqueConstraint("endpoint", name="uq_push_subscriptions_endpoint"),
    )
    op.create_index("ix_push_subscriptions_user_id", "push_subscriptions", ["user_id"])


def downgrade() -> None:
    op.drop_table("push_subscriptions")
    op.drop_table("settings")
    op.drop_table("verification_codes")
    op.drop_table("order_events")
    op.execute("ALTER TABLE orders DROP CONSTRAINT IF EXISTS excl_orders_driver_overlap")
    op.execute("DROP FUNCTION IF EXISTS order_busy_range(timestamptz, smallint)")
    op.drop_table("orders")
    op.drop_table("addresses")
    op.drop_table("driver_time_off")
    op.drop_table("driver_schedule")
    op.drop_table("drivers")
    op.drop_table("users")
